# Generated by Django 5.0 on 2023-12-18 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("called_at", models.DateTimeField(auto_now_add=True)),
                ("numbers", models.CharField(max_length=50, null=True)),
                ("contents", models.TextField(null=True)),
                ("audio_file", models.FileField(null=True, upload_to="audio/")),
                ("results", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Organizations",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("image", models.CharField(max_length=255)),
                ("call", models.CharField(max_length=50)),
                ("work", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Text_KorCCVi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("transcript", models.TextField()),
                ("label", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Text_mail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("label", models.BooleanField(null=True)),
                ("phone_number", models.CharField(max_length=50, null=True)),
                ("message_embedding", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MelSpectrograms",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mel_img",
                    models.ImageField(null=True, upload_to="mel_spectrograms_img/"),
                ),
                (
                    "mel_np",
                    models.FileField(null=True, upload_to="mel_spectrogram_np/"),
                ),
                ("category", models.CharField(max_length=10, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "call_history",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mel_spectrograms_data",
                        to="phishing.callhistory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="callhistory",
            name="mel_spectrogram",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_history_mel_spectrogram",
                to="phishing.melspectrograms",
            ),
        ),
        migrations.CreateModel(
            name="MFCC",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mfcc", models.FileField(null=True, upload_to="mfcc/")),
                ("category", models.CharField(max_length=10, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "call_history",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfcc_data",
                        to="phishing.callhistory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="callhistory",
            name="mfcc",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_history_mfcc",
                to="phishing.mfcc",
            ),
        ),
    ]
